footprint: [[-1.75, -2.5], [-1.75, 2.5], [1.75, 2.5], [1.75, -2.5]]
footprint_padding: 0.01

robot_base_frame: wamv/base_link
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 10.0
raytrace_range: 3.0

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser_scan
    laser_scan: {data_type: LaserScan, clearing: true, marking: true, topic: laser_scan, inf_is_valid: true}

inflation:
    inflation_radius: 2.5
